[window]
opacity = 0.95
blur = true

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001b\r" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
